#!/bin/bash
usage()
{
    echo "usage: setup <location>\n"
    echo "<location>  One of 'home' or 'work'"
}

case $1 in
    home | work )  location=$1
            shift
            ;;
    * )     usage
            exit 1
esac

#####
##### Set up symlinks
#####

symlinks -l "$location"

#####
##### Install Homebrew
#####

ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

###
### Install Homebrew and Cask packages
###

brew bundle Caskfile
