#!/bin/bash
# Set up symlinks if they don't already exist.
for file in {bash_profile,bash_prompt,aliases}; do
  [ -L ~/."$file" ] && rm ~/."$file"
  [ ! -e ~/."$file" ] && ln -s ~/.dotfile/"$file" ~/."$file"
done

[ -L ~/.extra ] && rm ~/.extra
[ ! -e ~/.extra ] && ln -s ~/.dotfile/extra/extra_home ~/.extra
