#!/bin/bash
usage()
{
	echo "usage: symlinks [-l location]"
}

# Parse parameters
location=_home

while [ "$1" != "" ]; do
	case $1 in
		-l | --location )	shift
					location=_$1
					;;
		* )			usage
					exit 1
	esac
	shift
done

# Set up symlinks if they don't already exist.
for file in {bash_profile,bash_prompt,aliases}; do
	[ -L ~/."$file" ] && rm ~/."$file"
	[ ! -e ~/."$file" ] && ln -s ~/.dotfile/"$file" ~/."$file"
done

# Set up extra configurations
for file in {extra,slate}; do
	[ -L ~/."$file" ] && rm ~/."$file"
	[ ! -e ~/."$file" ] && ln -s ~/.dotfile/configs/"$file$location" ~/."$file"
done
